# Site settings
title: MPow
email: manzopower@icloud.com
description: "iOS and OSX Developer"
baseurl: ""
url: "http://blog.mpow.it"
twitter_username: ManzoPower
github_username:  MP0w

# Build settings
markdown: kramdown
permalink: "/:title"


production: true
timezone: "Europe/Rome"

author:
    display_name: Alex Manzella
    username: MPow
    
assets-path: "../assets/"
cover: "root.jpg"