# Site settings
title: MPow
description: "Tech Lead @ Amie"
defaultTags: "mpow, manzopower, mp0w, blog, ios, developer, osx, cocoa, UIKit, miniplayer, animateall, powermusic"

email: m@mpow.dev
baseurl: ""
url: "https://mpow.dev"
twitter_username: manzopower
github_username: MP0w
job_title: "Tech Lead"
job_website: "https://amie.so"
job_company: "Amie"

# Build settings
markdown: kramdown
permalink: "/:title"

production: true
timezone: "Europe/Rome"

author:
    display_name: Alex Manzella
    username: MPow
